"""GitHubClient protocol — the interface both real and fake clients implement."""

from __future__ import annotations

from typing import Any, Protocol

from ai_pr_orchestrator.github import models


class GitHubClient(Protocol):
    """Structural typing interface for GitHub API operations."""

    def get_pr(self, number: int) -> models.PullRequest: ...

    def get_pr_files(self, pr_number: int) -> list[str]: ...

    def get_pr_comments(self, issue_number: int) -> list[models.Comment]: ...

    def get_comment(self, comment_id: int) -> models.Comment | None: ...

    def post_comment(self, issue_number: int, body: str) -> models.Comment: ...

    def edit_comment(self, comment_id: int, body: str) -> models.Comment: ...

    def get_labels(self, issue_number: int) -> list[str]: ...

    def list_issues_by_label(self, label: str) -> list[int]: ...

    def add_label(self, issue_number: int, label: str) -> list[dict[str, Any]]: ...

    def remove_label(self, issue_number: int, label: str) -> None: ...

    def get_check_runs(self, ref: str) -> list[models.CheckRun]: ...

    def get_commit_statuses(self, ref: str) -> list[models.CheckRun]: ...

    def get_pull_request_reviews(self, pr_number: int) -> list[models.Review]: ...

    def get_review_threads(self, pr_number: int) -> list[models.ReviewThread]: ...

    def reply_to_review_thread(self, thread_id: str, body: str) -> dict[str, Any] | None: ...

    def resolve_review_thread(self, thread_id: str) -> dict[str, Any] | None: ...
